apiVersion: v1
kind: ServiceAccount
metadata:
  name: assura-backend
  labels:
    {{- include "assura-backend.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
